version: "3.9"
services:
  duplicity:
    build:
      args:
        ALPINE_VERSION: "latest"
        CONTAINER_VERSION: "2.1.4"
        DUPLICITY_VERSION: "2.1.4"
      context: .
      dockerfile: container.build
      no_cache: true  
      
      tags:
        - "duplicity:build"
        - "gautada/duplicity:build"
        - "gautada/duplicity:latest"
    image: "gautada/duplicity:latest"
    volumes:
      - "Container:/mnt/volumes/container"
      - "Backup:/mnt/volumes/backup"
      - "Configmaps:/mnt/volumes/configmaps"
      - "Secrets:/mnt/volumes/secrets"


volumes:
  Container:
    external: true
    name: "Container"

  Backup:
    external: true
    name: "Backup"

  Configmaps:
    external: true
    name: "Configmaps"
    
  Secrets:
    external: true
    name: "Secrets"
    
